import pandas as pd
import io

def select_row_by_iloc(df: pd.DataFrame, index: int):
    """
    Selects a specific row from a DataFrame using its positional (integer) index.

    Args:
        df: The Pandas DataFrame.
        index: The 0-based integer index of the row to select.
    """
    print(f"\n--- Attempting to select row at positional index: {index} ---")
    
    try:
        # The .iloc[] indexer is used for selection by INTEGER position.
        # It handles both Series and DataFrames.
        selected_row = df.iloc[index]
        
        # Display the result
        print("Successfully selected row:")
        # The result is a Pandas Series where the column names become the index.
        print(selected_row)
        
    except IndexError:
        print(f"Error: Index {index} is out of bounds for the DataFrame (size {len(df)}).")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# --- Test Data Setup ---
# The provided data is somewhat messy, so we use string manipulation to parse it.
data = """
0        s001     V  Alberto Franco     15/05/2002      35  street1   t1
1        s002     V    Gino Mcneill     17/05/2002      32  street2   t2
2        s003    VI     Ryan Parkes     16/02/1999      33  street3   t3
3        s001    VI    Eesha Hinton     25/09/1998      30  street1   t4
4        s002     V    Gino Mcneill     11/05/2002      31  street2   t5
5        s004    VI    David Parkes     15/09/1997      32  street4   t6
"""

# Read the data, treating multiple spaces as a single separator
df = pd.read_csv(
    io.StringIO(data), 
    sep=r'\s+', 
    engine='python', 
    header=None,
    skiprows=1  # Skip the header row '0', '1', '2', etc. generated by the IO process
)

# Assign meaningful column names
df.columns = ['ID_Num', 'Class', 'Name', 'DOB', 'Age', 'Address', 'Tag']

# --- Execution ---

print("--- Original DataFrame (with Positional Indices 0-5) ---")
print(df)
print("-" * 60)

# 1. Select the 3rd row (0-based index 2)
select_row_by_iloc(df, 2)

# 2. Select the last row (0-based index 5)
select_row_by_iloc(df, 5)

# 3. Demonstrate out-of-bounds error
select_row_by_iloc(df, 10)